services:
  # Development environment with hot-reload
  app-dev:
    container_name: go-sse-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./configs:/app/configs
    environment:
      - APP_ENV=dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - go-sse-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# กำหนดเครือข่ายสำหรับ containers
networks:
  go-sse-network:
    driver: bridge 