services:
  # UAT environment
  app-uat:
    container_name: go-sse-uat
    build:
      context: .
      dockerfile: Dockerfile
      target: uat
      args:
        - BUILD_ENV=uat
    ports:
      - "8082:8080"
    environment:
      - APP_ENV=uat
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - go-sse-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# กำหนดเครือข่ายสำหรับ containers
networks:
  go-sse-network:
    name: go-sse-network-uat
    driver: bridge 